### ISSUE TITLE
Data sets don't work as expected in a multisite installation

### ISSUE THREAD

**Issue by superextinct** [barrelstrength/sprout-data-studio#3]
### Description

After migrating vom Sprout Reports to Data Studio, existing data sets were assigned to the default site. As some users only have access to specific sites other than the default site, they are not able to view these data sets, reports or export them. 

AFAIK there's currently no way through the control panel, to assign data sets to a different site. I've tried doing this manually in the database, by changing the siteId of associated rows inside `elements_sites` and `content`. That works to a degree, as I can now see the data set within the element index page. Trying to view the report however, returns a `NotFoundHttpException`. This is somewhat expected, as the element query does not take the current site into account:

```php
// src/datastudio/controllers/DataSetController.php

public function actionResultsIndexTemplate(DataSetElement $dataSet = null, int $dataSetId = null): Response
{
    if ($dataSet === null && $dataSetId) {
        $dataSet = Craft::$app->elements->getElementById($dataSetId, DataSetElement::class);
    }

    if (!$dataSet) {
        throw new NotFoundHttpException('Data set not found.');
    }
 // …
```

In this instance, this could be solved by:

```php
$siteHandle = $this->request->getQueryParam('site');
$siteId =  $siteHandle ? Craft::$app->getSites()->getSiteByHandle($siteHandle)->id : null;
$dataSet = Craft::$app->elements->getElementById($dataSetId, DataSetElement::class, $siteId);
```

I'm not confident in writing this as a PR since there might be more work needed in other places. It's not super relevant to my use case, but trying to create a new data set in any site other than the default site throws an error as well (draft ID only exists for default site).

### How to reproduce

Craft needs to have at least two sites configured: Default site A and another site B. Open Data Studio and select site B. Create a new data set. After saving, this data set won't be available for site B, but for default site A.

Create a new user, that does not have permission to access site A, but has access to site B. Try to create a new data set.

### Sprout Version

4.0.3

### Craft Version

4.4.5

### Database Type Version

MySQL 8.0.26

**Comment by BenParizek** [comment]
This issue is fixed and tagged in the [4.45.0](https://github.com/barrelstrength/sprout-data-studio/releases/tag/4.45.0) release but not yet showing up in the plugin store. I've got a ticket open trying to sort that out and will update here once I do. 

While it may no longer be an issue for you, I wasn't able to replicate the issue with the migration changing the site IDs to the primary site. However, there was a bug in how Data Sets were being saved where they were always saving to the primary site. So my best guess about the migration right now is that it went fine and it was after the migration when you updated or saved some entries trying to figure out the multi-site stuff that those entries got resaved to the primary site.

**Comment by BenParizek** [comment]
The 4.45.0 release is now up in the plugin store. Thanks for reporting.

**Comment by superextinct** [comment]
Hi @BenParizek, thank you for this! Creating a new data set works fine now. Updating or exporting a data set still throws a NotFound Exception. I've created a PR that adds the same changes for these two actions: https://github.com/barrelstrength/sprout/pull/24
